export const EXAMPLES = [
  {
    id: 'baile-funk-das-antigas',
    title: 'O baile das antigas ainda move a pista',
    category: 'Música',
    eyebrow: 'Encontro de gerações',
    summary: 'Naldo, DJ Marlboro, MC Nem e Bonde 2000 se encontram em uma edição dedicada à memória e à força do funk.',
    body: 'O Segue o Baile TV reuniu nomes que ajudaram a escrever capítulos do funk em uma edição dedicada ao baile das antigas. Entre histórias, música e reencontros, o vídeo celebra a cena que continua inspirando novas gerações.\n\nAssista à cobertura completa no canal e confira cada conversa diretamente com seus protagonistas.',
    youtubeId: 'xRmK5hE16ko',
    publishedAt: null,
    author: 'Redação Segue o Baile TV',
    featured: true,
  },
  {
    id: 'jojo-toddynho',
    title: 'Jojo Toddynho fala sobre faculdade e carreira musical',
    category: 'Entrevistas',
    eyebrow: 'Conversa aberta',
    summary: 'Em entrevista ao canal, Jojo abre espaço para falar de estudos e do caminho que vem construindo na música.',
    body: 'Jojo Toddynho é a convidada desta conversa do Segue o Baile TV. O assunto passa pela faculdade e pela carreira musical — duas frentes que aparecem no título da entrevista publicada pelo canal.\n\nDê o play para acompanhar as respostas na íntegra, sem tirar a conversa de contexto.',
    youtubeId: '5BkZ09SDxOU',
    publishedAt: null,
    author: 'Redação Segue o Baile TV',
  },
  {
    id: 'mc-poze-chefin-borges',
    title: 'MC Poze, Chefin e Borges: a voz do Complexo do Alemão',
    category: 'Música',
    eyebrow: 'Na cena',
    summary: 'Uma cobertura com três nomes da música e uma mensagem sobre a potência cultural do Complexo do Alemão.',
    body: 'A edição do Segue o Baile TV acompanha MC Poze, Chefin e Borges em um encontro ligado ao Complexo do Alemão. O vídeo coloca a música e seus artistas no centro da conversa.\n\nAssista ao material original para conhecer o contexto completo e ouvir os protagonistas.',
    youtubeId: 'vBOAohQbZJg',
    publishedAt: null,
    author: 'Redação Segue o Baile TV',
  },
  {
    id: 'carnavoz-2025',
    title: 'Segue o Baile TV invade o Carnavoz 2025',
    category: 'Coberturas',
    eyebrow: 'Na rua',
    summary: 'A equipe chega ao Carnavoz para uma cobertura especial com entrevistas e bastidores do evento.',
    body: 'O Segue o Baile TV foi ao Carnavoz 2025 para registrar o clima do evento e conversar com quem faz a festa acontecer. A cobertura em vídeo é o ponto de partida desta matéria.\n\nVeja a edição completa no canal para acompanhar as entrevistas e os momentos registrados pela equipe.',
    youtubeId: 'ikauA4VP_Aw',
    publishedAt: null,
    author: 'Redação Segue o Baile TV',
  },
  {
    id: 'vitinho-ilha-da-gigoia',
    title: 'Vitinho agita a Ilha da Gigóia',
    category: 'Coberturas',
    eyebrow: 'Exclusivo',
    summary: 'Uma passagem pela Ilha da Gigóia com Vitinho em destaque na cobertura do canal.',
    body: 'A Ilha da Gigóia é cenário desta edição com Vitinho. O Segue o Baile TV acompanhou o momento de perto e reuniu tudo em vídeo.\n\nAssista à cobertura para ver os registros da equipe.',
    youtubeId: 'MhaYlLIOo0g',
    publishedAt: null,
    author: 'Redação Segue o Baile TV',
  },
  {
    id: 'joao-da-verde-e-rosa',
    title: 'João da Verde e Rosa conta sua história de superação',
    category: 'Histórias',
    eyebrow: 'Gente que faz',
    summary: 'Na Mangueira, João da Verde e Rosa compartilha sua trajetória em conversa com o Segue o Baile TV.',
    body: 'O Segue o Baile TV foi à Mangueira, no Rio de Janeiro, para conversar com João da Verde e Rosa. O vídeo apresenta sua história de superação em suas próprias palavras.\n\nA entrevista completa está disponível no canal.',
    youtubeId: '2r_2mpd4uUA',
    publishedAt: null,
    author: 'Redação Segue o Baile TV',
  },
];
